### ISSUE TITLE
Joint Ordering

### ISSUE THREAD

**Issue by ryan-seungyong-lee** [MartaYang/KITRO#4]
https://docs.google.com/spreadsheets/d/1_1dLdaX-sbMkCKr_JzJW_RZCpwBwd7rcKkWT_VgAQ_0/edit#gid=0

When I tried to share the above document about joint ordering, I accidentally changed the availability of the document to restricted.
Could you please reshare the link above, it's currently restricted. I apologize.

Thanks, Seungyong Lee

**Comment by MartaYang** [comment]
Hi, I’m also unable to access the sheet you provided, likely because it was originally shared by the authors of EFT. You might want to reach out to them directly for access. Alternatively, here’s a [copy of the original sheet](https://docs.google.com/spreadsheets/d/14KmTPRwtTg8R30kvoP5-U2GciR8Xw6BvmxRzKc--hBs/edit?usp=sharing) that might help. I hope this works for you!

**Comment by ryan-seungyong-lee** [comment]
Thx :)
